### ISSUE TITLE
Font in settings is same color as background on iPad

### ISSUE THREAD

**Issue by danieltaylor** [hbang/NewTerm#21] opened 2014-07-06 04:03 UTC
http://imgur.com/DNsP6gp

The font for the preferences are the same color as the background.  It is only readable if you tap and hold the option.

iPad Air, iOS 7.0.6

**Comment by kousu** [comment] 2016-01-24 05:02
:+1: I installed from Cydia just now and found this problem.

**Comment by kirb** [comment] 2016-08-31 04:37
Closing as duplicate of #13.

**Closed by kirb** 2016-08-31 04:37 UTC
Labels: bug
