### ISSUE TITLE
SESSION ENDED

### ISSUE THREAD

**Issue by CHAMALY** [hbang/NewTerm#102] opened 2024-02-29 04:32 UTC
![C658D0CD-AA71-4C48-AC0C-40F95178DB27](https://github.com/hbang/NewTerm/assets/154996532/e88c6875-8a3b-461c-bf2c-b468ed0bbe3f)
 I CAN’T USE TERMINAL 
IPHONE 13pm DOPAMINE JAILBREAK

**Comment by iAdam1n** [comment] 2024-02-29 11:07
You need to install gettext-localizations and reinstall system-cmds. Duplicate of #91.

**Closed by iAdam1n** 2024-02-29 11:07 UTC

**Comment by CHAMALY** [comment] 2024-03-07 19:43
> You need to install gettext-localizations and if that doesnt work, reinstall system-cmds. Duplicate of #91.

Not work 😢

**Comment by iAdam1n** [comment] 2024-03-11 03:39
This should be fixed with Dopamine 2.0.11.
